language: node_js
before_install:
- npm install -g typescript
- npm install -g sass
install:
- npm install
jobs:
  include:
  - stage: build
    script: "./build.sh"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  on:
    branch: master
  local_dir: public
  fqdn: invoice.ophie.io
env:
  matrix:
    secure: HI3iq6lMkaQ0H20JcOC92Q8zkHUwb9yHlg27md+9LVdkr0XYWmXrOGjNPPEilnfAgwvfY0alxG5xbGQsrPmIXkUdPrsraLLTiN6X2mKSUDTga8pCMIUW3w5eE3Ubr2HZP5+agC1ddsuj+GOa20NG1u2cqoToievUE7ibNFmjaBfBKWtAsMiZyMCA/L1yokux8swRtTTU3ClP6Jw31zC8oo4WSfJqAB7DLwUd2bnQn9kU/Sb9cEVGsQIMngLfGDMv63PuKM70Ljv+U11rbIvSP0OSYqjpJZrJ4BXuyHtxoxPY3NMQ+MveWTQ404552KoboGikSuoc4v79ZDcpt64kWn0rWskJlln7eMD7qzDrhYXHF6Ifwygcj+3WSfOt/P+qHpiydwM1fZx887a0E+1FzJWeShuvxtb7M0MEBFfawyEW7Fmcdw2bdn+Y8mEx2JccJcn38SjDFfQILi4wT29Xj5F1MrisB5mE+a7gpm5EheK33SS4MqBywPAn1CTqxfXnSHlcbnuakBygvQUcLrG87g68/hTG7fmmYyjSPNEu6kKcX+eIZtunFkLJbwreQaEK4uyDRXyrNUm21VPak0cbnE5Fr92I8UWFacMEmgvtws9nGRO59jQI4x5xVQ0PqKeha9lCMgwDwI2NdJhEuNIEG+YyVCzoi/Q2l/YXYqaeJA8=
